name: voice_image_sync
description: Audio + TXT script + images to MP4 video.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter_new: ^4.1.0
  file_picker: 8.3.7
  gal: ^2.3.1
  path_provider: ^2.1.5

flutter:
  uses-material-design: true
